services:
  - type: web
    name: cruisetracker
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn cruisetracker.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: cruisetracker.settings
      - key: PYTHONUNBUFFERED
        value: 1
      - key: DATABASE_URL
        fromDatabase:
          name: cruisetracker-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: price-tracking-project.onrender.com
      - key: DEBUG
        value: false

  - type: pserv
    name: cruisetracker-db
    env: postgresql
    plan: free 